PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "migrations" ("id" integer primary key autoincrement not null, "migration" varchar not null, "batch" integer not null);
INSERT INTO migrations VALUES(2,'0001_01_01_000001_create_cache_table',1);
INSERT INTO migrations VALUES(3,'0001_01_01_000002_create_jobs_table',1);
INSERT INTO migrations VALUES(5,'2026_08_22_082102_create_articles_table',2);
INSERT INTO migrations VALUES(6,'0001_01_01_000000_create_users_table',3);
INSERT INTO migrations VALUES(7,'2026_08_22_093259_add_article_fields_to_articles_table',4);
INSERT INTO migrations VALUES(8,'2026_08_22_095648_create_products_table',5);
INSERT INTO migrations VALUES(9,'2026_08_22_102549_create_galleries_table',6);
CREATE TABLE IF NOT EXISTS "cache" ("key" varchar not null, "value" text not null, "expiration" integer not null, primary key ("key"));
CREATE TABLE IF NOT EXISTS "cache_locks" ("key" varchar not null, "owner" varchar not null, "expiration" integer not null, primary key ("key"));
CREATE TABLE IF NOT EXISTS "jobs" ("id" integer primary key autoincrement not null, "queue" varchar not null, "payload" text not null, "attempts" integer not null, "reserved_at" integer, "available_at" integer not null, "created_at" integer not null);
CREATE TABLE IF NOT EXISTS "job_batches" ("id" varchar not null, "name" varchar not null, "total_jobs" integer not null, "pending_jobs" integer not null, "failed_jobs" integer not null, "failed_job_ids" text not null, "options" text, "cancelled_at" integer, "created_at" integer not null, "finished_at" integer, primary key ("id"));
CREATE TABLE IF NOT EXISTS "failed_jobs" ("id" integer primary key autoincrement not null, "uuid" varchar not null, "connection" text not null, "queue" text not null, "payload" text not null, "exception" text not null, "failed_at" datetime not null default CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS "articles" ("id" integer primary key autoincrement not null, "created_at" datetime, "updated_at" datetime, "title" varchar not null, "content" text not null, "image" varchar);
INSERT INTO articles VALUES(2,'2026-08-22 10:48:59','2026-08-22 10:48:59','hutan manusia',unistr('Y8D\u000d\u000aAngela Lie\u000d\u000a15/11/2023\u000d\u000aHUTAN INDONESIA\u000d\u000aKenapa hutanya Indonesia perlu dikonversasi?\u000d\u000aIndonesia adalah salah satu tempat dengan hutan terluas dan hijau, tetepi, hutanya Indoneesia juga sangat perlu untuk melakukan konservasi.\u000d\u000aPasti kamu tanya kenapa kita harus melakukan konservasi terhadap hutan hutan ini? Kita harus konversasi hutan tersebut karena hutan hutan ini menyediakan keseimbangan ekologis alam bumi, dan juga ada banyak fungsi berbagai berikut.\u000d\u000a4 Fungsi Hutan Hutan Indonesia\u000d\u000a1. Mencegah erosi dan tanah longsor. Akar pohon berfungsi sebagai pengikat butiran tanah, dan akan menghindari tanah longsar karena tanahnya akan lebih kompak dan kuat.\u000d\u000a2. Untuk menjaga, mengatur, dan memelihara persediaan air. Kita perlu menghemat air dengan memanfaatkan tanaman, terutama pada musim hujan, karena air akan semakin langka dan kemungkinan kematian tanaman semakin besar, sehingga pada akhimya musim akan semakin panas jika kita tidak menjaga hutan.\u000d\u000a3. Sebagai pupuk tanah. Semakin banyak daun yang gugur dari pohon maka semakin banyak pula pupuk yang dimiliki tanah, semakin banyak tanaman yang dapat tumbuh, dan mampu menyediakan. lebih banyak sumber daya alam baik berupa tanaman, kayu, dan lain-lain.\u000d\u000a4. Untuk mengurangi polusi udara. Tumbuhan menyerap karbon dioksida dan menghasilkan oksigen yang dibutuhkan oleh makhluk hidup.\u000d\u000aSekarang, kami sudah memberitahukan fungsi fungsi hutan Indonesia, dan kenapa kita harus melakukan konservasi kepadanya. Ayolah kita mengubah diri kita untuk menjadi lebih hebat kepada negara dan Bumi kita!'),'articles/VuyPSF4o8e8LDSupdjlf5za16ON3O9vRWBVpgpin.jpg');
CREATE TABLE IF NOT EXISTS "users" ("id" integer primary key autoincrement not null, "name" varchar not null, "email" varchar not null, "email_verified_at" datetime, "password" varchar not null, "remember_token" varchar, "created_at" datetime, "updated_at" datetime);
INSERT INTO users VALUES(1,'Admin','admin@gmail.com',NULL,'$2y$12$CusgIfo.ck9UBdwUXtjpU.ur35K6xf9VEoV9FHI1SDKFF5yAbofOm',NULL,'2026-08-22 09:14:48','2026-08-22 09:14:48');
CREATE TABLE IF NOT EXISTS "products" ("id" integer primary key autoincrement not null, "name" varchar not null, "description" text not null, "price" numeric, "image" varchar, "created_at" datetime, "updated_at" datetime);
INSERT INTO products VALUES(2,'laptop','MacBook Neo adalah laptop pemula (entry-level) terjangkau dari Apple berbobot 1,23 kg. Laptop ini mengandalkan chip A18 Pro, layar Liquid Retina 13 inci (500 nit), serta baterai tahan hingga 16 jam, menjadikannya pilihan ekonomis berbalut bodi aluminium kokoh untuk tugas harian.',14000014,'products/DbPNp9sC0ZBXUonpqg6zx1iFHElae54k1aKdoj6T.webp','2026-08-22 10:24:28','2026-08-22 10:24:28');
CREATE TABLE IF NOT EXISTS "galleries" ("id" integer primary key autoincrement not null, "title" varchar not null, "image" varchar not null, "description" text, "created_at" datetime, "updated_at" datetime);
INSERT INTO galleries VALUES(2,'Ruang Kerja Utama','galleries/PdBQwA12PhBog9fD4QlfMXNUPkZNk2MvE95FJhuT.jpg','Suasana area kerja terbuka yang modern dan nyaman untuk mendukung kolaborasi antar tim setiap hari.','2026-08-22 10:52:52','2026-08-22 10:52:52');
INSERT INTO sqlite_sequence VALUES('migrations',9);
INSERT INTO sqlite_sequence VALUES('users',1);
INSERT INTO sqlite_sequence VALUES('articles',2);
INSERT INTO sqlite_sequence VALUES('products',2);
INSERT INTO sqlite_sequence VALUES('galleries',2);
CREATE INDEX "cache_expiration_index" on "cache" ("expiration");
CREATE INDEX "cache_locks_expiration_index" on "cache_locks" ("expiration");
CREATE INDEX "jobs_queue_index" on "jobs" ("queue");
CREATE UNIQUE INDEX "failed_jobs_uuid_unique" on "failed_jobs" ("uuid");
CREATE UNIQUE INDEX "users_email_unique" on "users" ("email");
COMMIT;
